version: "3.2"

services:

  functions:
    image: functions-template:v2.0.0
    build:
      context: ./
      dockerfile: docker/functions/Dockerfile
    env_file: 
      - .env
    environment:
      - languageWorkers__node__arguments=--inspect=0.0.0.0:5858
    working_dir: /usr/src/app
    ports:
      - "7071:7071"
      - "5858:5858"
    networks:
      - io-fn
    depends_on:
      - fnstorage
    volumes:
      - .:/usr/src/app

  fnstorage:
    image: azurite
    build:
      context: ./
      dockerfile: docker/azurite/Dockerfile
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - io-fn

  storage:
    image: azurite
    command: ["sh", "-c", "node bin/azurite -l /opt/azurite/folder --blobPort 10003 --queuePort 10004 --tablePort 10005"]
    ports:
      - "10003:10003"
      - "10004:10004"
      - "10005:10005"
    depends_on:
      - fnstorage
    networks:
      - io-fn

networks:
  io-fn:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
